
configfile: "config.yaml"

rule check_rfam:
    input:
        rfam="/home/rnahub/rnahub/db/rfam/Rfam.cm",
        fasta=expand("{seq}", seq=config["fasta"]),
        seed="/home/rnahub/rnahub/db/rfam/Rfam.seed.gz"
    output:
        "/home/pearljen/test/rfam_result.txt"
    shell:
        'python3 /home/pearljen/repo/rnahub/search_rfam.py --rfam {input.rfam} --fasta {input.fasta} --seed {input.seed} > {output}'